name: tagflow

packages:
  - packages/**
  - examples/**

scripts:
  docs:
    exec: dartdoc
    description: Generate documentation
  analyze:
    exec: dart analyze .
    description: Analyze the project
  test:
    exec: flutter test
    description: Run tests