name: tagflow
description: "A new Flutter package project."
version: 0.0.1+dev.1
homepage: https://tagflow.arya.run
license: ../../LICENSE

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
