name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Clean & Bootstrap
        run: melos bootstrap:clean

      - name: Get Dependencies
        run: melos run pub:get

      - name: Validate
        run: melos run validate
