name: Publish packages to pub.dev

on:
  push:
    tags:
      - "tagflow*-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Extract package name from tag
      - name: Extract package name
        id: extract_package
        run: |
          TAG=${{ github.ref_name }}
          # Extract everything before -v, handling both hyphen and underscore cases
          PACKAGE_NAME=$(echo $TAG | perl -pe 's/(?:-v|\bv)[0-9]+\.[0-9]+\.[0-9]+.*$//')
          echo "Extracted tag: $TAG"
          echo "Extracted package name: $PACKAGE_NAME"
          echo "Working directory will be: packages/$PACKAGE_NAME"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "working_directory=packages/$PACKAGE_NAME" >> $GITHUB_OUTPUT

      # Set up Dart SDK and provision OIDC token
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672

      # Setup Flutter - needed for publishing Flutter packages
      - uses: flutter-actions/setup-flutter@d030cb603380106494f72d65a7e52462f380781f

      # Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing dependencies in ${{ steps.extract_package.outputs.working_directory }}"
          dart pub get
        working-directory: ${{ steps.extract_package.outputs.working_directory }}

      # Dry run
      - name: Publish - dry run
        run: dart pub publish --dry-run
        working-directory: ${{ steps.extract_package.outputs.working_directory }}

      # Publish to pub.dev
      - name: Publish to pub.dev
        run: dart pub publish -f
        working-directory: ${{ steps.extract_package.outputs.working_directory }}
