name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          flutter pub get
          dart pub global activate coverage
          dart pub global activate melos
          melos bootstrap

      - name: Run tests with coverage
        run: |
          melos run coverage
          melos run combine-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
