name: Create Dev Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
          run-versioning-prerelease: true
          create-pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUB_CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}

      - name: Create Git Tags
        run: |
          melos version --yes --no-git-tag-version --prerelease
          melos exec -c 1 --no-private -- "git tag \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION"
          git push origin --tags
