name: Create Dev Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    if: "${{ !contains(github.event.head_commit.message, 'chore(release): Publish packages') }}"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
          run-versioning-prerelease: true
          create-pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUB_CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}

      - name: Create Git Tags and Generate Changelog
        id: release
        run: |
          # Run version command and capture new version
          melos version --yes --no-git-tag-version --prerelease

          # Generate the changelog
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          melos changelog >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Get the version for the release title
          VERSION=$(melos list --json | jq -r '.[0].version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Create and push tag
          melos exec -c 1 --no-private -- "git tag \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION"
          git push origin --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tagflow-v${{ env.VERSION }} # set by previous step
          name: Release v${{ env.VERSION }} # set by previous step
          body: ${{ env.CHANGELOG }} # set by previous step
          prerelease: true # Since these are dev releases
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
